

@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR Advisor" {
    usecase UC1 as "All the countries in the
    world, continents, regions,
     are organized from
     largest to smallest population.
    "

    usecase UCa as "Population"

    HR - UC1
    UC1 ..> UCa : include
    UC1 - Database
}

@enduml