

@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get countries in a continent
    by population size"

    usecase UCa as "Population"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml