

@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "All the countries in the
    world, continents, regions,
     are organized from
     largest to smallest population.
    "

    usecase UCa as "Population"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml